export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://www.app.a2v2.ai'
export const CHAT_EMBED_URL = process.env.NEXT_PUBLIC_CHAT_EMBED_URL || 'https://chat.a2v2.ai/6997ccdf7498815679b412d8'
export const CHAT_WIDGET_URL = process.env.NEXT_PUBLIC_CHAT_WIDGET_URL || 'https://chat-widget.a2v2.ai/embed.js'
export const DEMO_BOOKING_URL = process.env.NEXT_PUBLIC_DEMO_BOOKING_URL || 'https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ1mosl4E14DaFo3zdh1kBAVaQm7utfpH2Ns0Xt2fmknpca-KOeaAoP_pTLfDoQa3eXV4luzv_Eb'
export const CHATBOT_ID = process.env.NEXT_PUBLIC_CHATBOT_ID || '6997ccdf7498815679b412d8'
